### ISSUE TITLE
Cannot delete a session because timeout keys are always added

### ISSUE THREAD

**Issue by dmichulke** [ring-clojure/ring-session-timeout#5]
Because the middleware always adds the timeout keys to the session, two things become impossible
- browsing the site without receiving a session/cookie
- deleting a session e.g. after logout (because the session data - with most parts removed - still exists)

This
- affects performance (DB reads/writes), 
- fills the session table / database (no automatic cleanup after logout possible) and 
- creates a timeout response some time in the future even if the user wasn't logged in in the first place.

Remedy: Only add timeout data to the session is session is not nil

**Comment by weavejester** [comment]
Are you using `wrap-idle-session-timeout`?

**Comment by dmichulke** [comment]
Yes, but it's a problem for both `wrap-idle-session-timeout` and `wrap-absolute-session-timeout`.

As a workaround I currently use a handler that wraps both:

```
(fn [h]
  ;; remove the timeouts if the session variable would be nil without them (otherwise this would prevent deleting sessions)
  (fn [req]
    (let [resp (h req)]
      (or (when-let [s (:session resp)]
            (when (empty? (dissoc s :ring.middleware.session-timeout/idle-timeout :ring.middleware.session-timeout/absolute-timeout))
              (assoc resp :session nil)))
          resp))))
```

**Comment by Pancia** [comment]
It looks like just doing a:

```
(cond-> session session
  (assoc ::*-timeout end-time))
```

at the bottom of `wrap-idle-session-timeout` and `wrap-absolute-session-timeout` fixes it.

**Comment by Pancia** [comment]
That doesn't sound right, it's the `:session` in the response that can be nil, not the response itself.

**Comment by weavejester** [comment]
Ah, whoops, looks like I solved a different issue.
